version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"  
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile-python
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydatabase
    networks:
      - mynetwork

networks:
  mynetwork:
